In [21]:
# ------------ FUNCTIONS ---------------

def merge(array, left, middle, right, param):
    n1 = middle - left + 1
    n2 = right - middle
    
    array1 = []
    array2 = []

    for i in range(n1): 
        array1.append(array[left + i])
        
    for j in range(n2):
        array2.append(array[middle + 1 + j])
  
    i = 0
    j = 0
    k = left
    
    while i < n1 and j < n2:
        if array1[i][param] <= array2[j][param]:
            array[k] = array1[i]
            i = i + 1
        else: 
            array[k] = array2[j]
            j = j + 1
        k = k + 1
        
        
    while i < n1:
        array[k] = array1[i] 
        i = i + 1
        k = k + 1
  
    while j < n2:
        array[k] = array2[j] 
        j = j + 1
        k = k + 1
        
    return array

def mergeSortAction(arr, left, right, param):
    if left < right: 
        middle = (left+(right-1))//2

        mergeSortAction(arr, left, middle, param) 
        mergeSortAction(arr, middle+1, right, param) 
        merge(arr, left, middle, right, param) 
    return arr

def mergeSort(arr, param):
    return mergeSortAction(arr, 0, len(arr)-1, param)

In [22]:
# INITIAL DATA

table1 = [
    {
        "age": 20,
        "name": "Oak",
        "salary": 345.20
    },
    {
        "age": 40,
        "name": "Birch",
        "salary": 120.33
    },
    {
        "age": 32,
        "name": "Maple",
        "salary": 345.20
    },
    {
        "age": 33,
        "name": "Poplar",
        "salary": 345.20
    }
]

table2 = [
    {
        "name": "Maple",
        "salary": 345.20,
        "type": 3
    },
    {
        "name": "Birch",
        "salary": 120.33,
        "type": 2
    },
    {
        "name": "Oak",
        "salary": 345.20,
        "type": 1
    },
    {
        "name": "Poplar",
        "salary": 345.20,
        "type": 4
    }
]

In [30]:
arr1 = mergeSort(table1, "age")

print("First table:")
for i in range(len(table1)):
    print(table1[i])

for i in range(len(arr1)):
    for j in range(len(arr1)):
        if(table2[j]["name"] == arr[i]["name"] and table2[j]["salary"] == arr[i]["salary"]):
            table2[i], table2[j] = table2[j], table2[i]
            break

print("\n Second table:")
for i in range(len(table2)):
    print(table2[i])

First table:
{'age': 20, 'name': 'Oak', 'salary': 345.2}
{'age': 32, 'name': 'Maple', 'salary': 345.2}
{'age': 33, 'name': 'Poplar', 'salary': 345.2}
{'age': 40, 'name': 'Birch', 'salary': 120.33}

 Second table:
{'name': 'Oak', 'salary': 345.2, 'type': 1}
{'name': 'Maple', 'salary': 345.2, 'type': 3}
{'name': 'Poplar', 'salary': 345.2, 'type': 4}
{'name': 'Birch', 'salary': 120.33, 'type': 2}